import { Mic, Map, Wallet, Calculator, Disc3, Film, Music } from 'lucide-react';

export interface AutomationDefinition {
  key: string;
  title: string;
  description: string;
  category: string;
  module: string;
  industryTip?: string;
  defaultTriggerDays: number | null; // null = immediate
  triggerDaysRange?: [number, number];
  defaultNotifyRole: string;
  defaultChannel: 'in_app' | 'email' | 'both';
  ctaLabel: string;
  recommended: boolean;
}

export const AUTOMATION_MODULES = [
  { id: 'booking', label: 'Booking', icon: Mic },
  { id: 'roadmaps', label: 'Hojas de Ruta', icon: Map },
  { id: 'finanzas', label: 'Finanzas', icon: Wallet },
  { id: 'presupuestos', label: 'Presupuestos', icon: Calculator },
  { id: 'discografica', label: 'Discográfica', icon: Disc3 },
  { id: 'sincronizaciones', label: 'Sincronizaciones', icon: Film },
  { id: 'artistas', label: 'Artistas', icon: Music },
] as const;

export const NOTIFY_ROLE_OPTIONS = [
  { value: 'equipo_booking', label: 'Equipo Booking' },
  { value: 'tour_manager', label: 'Tour Manager' },
  { value: 'administracion', label: 'Administración' },
  { value: 'equipo_marketing', label: 'Equipo Marketing' },
  { value: 'artista', label: 'Artista' },
  { value: 'yo', label: 'Yo mismo' },
  { value: 'promotor', label: 'Promotor (externo)' },
  { value: 'sello', label: 'Sello (externo)' },
];

export const CHANNEL_OPTIONS = [
  { value: 'in_app', label: 'In-app' },
  { value: 'email', label: 'Email' },
  { value: 'both', label: 'Ambos' },
] as const;

export const AUTOMATIONS: AutomationDefinition[] = [
  // ── BOOKING: Gestión de Ofertas ──
  {
    key: 'booking_offer_no_response',
    title: 'Oferta sin respuesta',
    description: 'Oferta en fase "Interés" sin actividad durante el periodo configurado.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'Las ofertas sin respuesta en 72h suelen perderse.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Enviar recordatorio al promotor',
    recommended: true,
  },
  {
    key: 'booking_negotiation_stalled',
    title: 'Negociación estancada',
    description: 'Oferta en "Negociación" sin cambios durante el periodo configurado.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    defaultTriggerDays: 5,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Registrar seguimiento',
    recommended: true,
  },
  {
    key: 'booking_check_availability',
    title: 'Consultar disponibilidad del equipo',
    description: 'Cuando una oferta pasa a "Negociación", notificar para confirmar disponibilidad.',
    category: 'Gestión de Ofertas',
    module: 'booking',
    industryTip: 'La disponibilidad debe confirmarse antes de cualquier negociación de condiciones.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Confirmar disponibilidad',
    recommended: true,
  },
  // ── BOOKING: Gestión de Contratos ──
  {
    key: 'booking_confirmed_no_contract',
    title: 'Evento confirmado sin contrato',
    description: 'Booking pasa a fase "Confirmado" sin contrato generado.',
    category: 'Gestión de Contratos',
    module: 'booking',
    industryTip: 'Ningún evento debe confirmarse sin respaldo contractual.',
    defaultTriggerDays: null,
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Generar Contrato',
    recommended: true,
  },
  {
    key: 'booking_contract_not_sent',
    title: 'Contrato sin enviar a firmar',
    description: 'Contrato generado pero no enviado a firmar.',
    category: 'Gestión de Contratos',
    module: 'booking',
    defaultTriggerDays: 1,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Enviar a firmar',
    recommended: true,
  },
  {
    key: 'booking_promoter_signature_pending',
    title: 'Firma del promotor pendiente',
    description: 'Contrato enviado pero sin firma del promotor.',
    category: 'Gestión de Contratos',
    module: 'booking',
    industryTip: 'El plazo estándar de firma en España es 7 días hábiles.',
    defaultTriggerDays: 5,
    triggerDaysRange: [1, 15],
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar firma al promotor',
    recommended: true,
  },
  {
    key: 'booking_signed_no_payment',
    title: 'Contrato firmado sin pago inicial',
    description: 'Contrato 100% firmado, sin pago del 50% registrado.',
    category: 'Gestión de Contratos',
    module: 'booking',
    industryTip: 'El 50% inicial debe cobrarse tras la firma del contrato.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar pago inicial (50%)',
    recommended: true,
  },
  // ── BOOKING: Producción y Logística ──
  {
    key: 'booking_roadmap_pending',
    title: 'Hoja de Ruta pendiente',
    description: 'Evento confirmado sin Hoja de Ruta asignada.',
    category: 'Producción y Logística',
    module: 'booking',
    defaultTriggerDays: 30,
    triggerDaysRange: [7, 60],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Crear Hoja de Ruta',
    recommended: true,
  },
  {
    key: 'booking_rider_missing',
    title: 'Rider técnico no subido',
    description: 'Evento sin rider en Archivos & Docs.',
    category: 'Producción y Logística',
    module: 'booking',
    industryTip: 'Los festivales requieren el rider con 15-21 días de antelación.',
    defaultTriggerDays: 21,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Subir Rider Técnico',
    recommended: true,
  },
  {
    key: 'booking_travel_expenses',
    title: 'Gastos de viaje sin estimar',
    description: 'Evento confirmado sin Travel Expenses registrados.',
    category: 'Producción y Logística',
    module: 'booking',
    defaultTriggerDays: 14,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Estimar gastos de viaje',
    recommended: false,
  },
  {
    key: 'booking_press_accreditations',
    title: 'Acreditaciones de prensa',
    description: 'Evento confirmado sin gestión de acreditaciones.',
    category: 'Producción y Logística',
    module: 'booking',
    industryTip: 'Los festivales cierran acreditaciones 2-3 semanas antes.',
    defaultTriggerDays: 21,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Gestionar acreditaciones',
    recommended: false,
  },
  // ── BOOKING: Comunicación ──
  {
    key: 'booking_announce_pending',
    title: 'Anuncio de concierto pendiente',
    description: 'Evento confirmado sin actividad de marketing registrada.',
    category: 'Comunicación y Promoción',
    module: 'booking',
    defaultTriggerDays: 14,
    triggerDaysRange: [7, 30],
    defaultNotifyRole: 'equipo_marketing',
    defaultChannel: 'in_app',
    ctaLabel: 'Registrar actividad de comunicación',
    recommended: false,
  },
  // ── BOOKING: Facturación ──
  {
    key: 'booking_final_payment',
    title: 'Pago final pendiente',
    description: 'Evento en fase "Facturado" sin cobro del 50% restante.',
    category: 'Facturación y Cierre',
    module: 'booking',
    defaultTriggerDays: 3,
    triggerDaysRange: [0, 7],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Reclamar pago final (50%)',
    recommended: true,
  },
  {
    key: 'booking_invoice_missing',
    title: 'Factura no subida post-evento',
    description: 'Evento pasado sin factura en Drive.',
    category: 'Facturación y Cierre',
    module: 'booking',
    industryTip: 'Las facturas deben emitirse en los 30 días posteriores al evento según normativa española.',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Subir factura',
    recommended: true,
  },
  {
    key: 'booking_economic_close',
    title: 'Cierre económico pendiente',
    description: 'Evento sin cierre económico registrado.',
    category: 'Facturación y Cierre',
    module: 'booking',
    defaultTriggerDays: 7,
    triggerDaysRange: [3, 30],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Completar cierre económico',
    recommended: true,
  },
  // ── HOJAS DE RUTA ──
  {
    key: 'roadmap_draft_pending',
    title: 'Hoja de Ruta en borrador',
    description: 'Hoja de Ruta sin publicar a pocos días del evento.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    defaultTriggerDays: 7,
    triggerDaysRange: [3, 14],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Publicar Hoja de Ruta',
    recommended: true,
  },
  {
    key: 'roadmap_hospitality_empty',
    title: 'Hospitalidad no completada',
    description: 'Bloque "Hospitalidad" vacío en la Hoja de Ruta.',
    category: 'Hojas de Ruta',
    module: 'roadmaps',
    defaultTriggerDays: 10,
    triggerDaysRange: [5, 21],
    defaultNotifyRole: 'tour_manager',
    defaultChannel: 'in_app',
    ctaLabel: 'Completar hospitalidad',
    recommended: false,
  },
  // ── FINANZAS ──
  {
    key: 'finance_fee_no_invoice',
    title: 'Fee sin factura asociada',
    description: 'Pago registrado sin factura vinculada.',
    category: 'Finanzas',
    module: 'finanzas',
    defaultTriggerDays: 5,
    triggerDaysRange: [1, 14],
    defaultNotifyRole: 'administracion',
    defaultChannel: 'in_app',
    ctaLabel: 'Vincular factura',
    recommended: true,
  },
  {
    key: 'finance_budget_unapproved',
    title: 'Presupuesto sin aprobar',
    description: 'Presupuesto generado sin aprobación.',
    category: 'Presupuestos',
    module: 'presupuestos',
    defaultTriggerDays: 3,
    triggerDaysRange: [1, 7],
    defaultNotifyRole: 'artista',
    defaultChannel: 'in_app',
    ctaLabel: 'Solicitar aprobación',
    recommended: true,
  },
  // ── DISCOGRÁFICA / SINCRONIZACIONES ──
  {
    key: 'sync_no_contract',
    title: 'Sincronización sin contrato',
    description: 'Sincronización en fase avanzada sin contrato.',
    category: 'Sincronizaciones',
    module: 'sincronizaciones',
    defaultTriggerDays: null,
    defaultNotifyRole: 'equipo_booking',
    defaultChannel: 'in_app',
    ctaLabel: 'Generar contrato de sincronización',
    recommended: true,
  },
  {
    key: 'release_master_pending',
    title: 'Masterización pendiente de entrega',
    description: 'Release con fecha pero sin master aprobado.',
    category: 'Discográfica',
    module: 'discografica',
    defaultTriggerDays: 30,
    triggerDaysRange: [14, 60],
    defaultNotifyRole: 'artista',
    defaultChannel: 'in_app',
    ctaLabel: 'Revisar estado del master',
    recommended: true,
  },
];
