project_id = "hptjzbaiclmgbvxlmllo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_runtime]
enabled = true
port = 54327

[functions.reindex-event]
verify_jwt = true

[functions.search-event-ai]
verify_jwt = false

[functions.setup-test-users]
verify_jwt = false

[functions.google-places-autocomplete]
verify_jwt = false

[functions.extract-contact-from-document]
verify_jwt = false

[functions.evaluate-automations]
verify_jwt = false

[functions.spotify-import]
verify_jwt = false