-- Add extended profile fields
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS stage_name text,
ADD COLUMN IF NOT EXISTS first_name text,
ADD COLUMN IF NOT EXISTS last_name text,
ADD COLUMN IF NOT EXISTS second_last_name text,
ADD COLUMN IF NOT EXISTS dni_nie text,
ADD COLUMN IF NOT EXISTS birth_date date,
ADD COLUMN IF NOT EXISTS social_security text,
ADD COLUMN IF NOT EXISTS street text,
ADD COLUMN IF NOT EXISTS postal_code text,
ADD COLUMN IF NOT EXISTS province text,
ADD COLUMN IF NOT EXISTS city text,
ADD COLUMN IF NOT EXISTS country text,
ADD COLUMN IF NOT EXISTS shoe_size text,
ADD COLUMN IF NOT EXISTS pants_size text,
ADD COLUMN IF NOT EXISTS shirt_size text,
ADD COLUMN IF NOT EXISTS jacket_size text,
ADD COLUMN IF NOT EXISTS height text,
ADD COLUMN IF NOT EXISTS allergies text,
ADD COLUMN IF NOT EXISTS is_smoker boolean DEFAULT false,
ADD COLUMN IF NOT EXISTS license_type text,
ADD COLUMN IF NOT EXISTS home_phone text,
ADD COLUMN IF NOT EXISTS iban text,
ADD COLUMN IF NOT EXISTS observations text;