INSERT INTO public.functional_role_default_permissions (role_name, module, level) VALUES 
('Mánager Personal','bookings','manage'::permission_level),
('Mánager Personal','budgets','manage'::permission_level),
('Mánager Personal','cashflow','manage'::permission_level),
('Mánager Personal','contracts','manage'::permission_level),
('Mánager Personal','releases','manage'::permission_level),
('Mánager Personal','projects','manage'::permission_level),
('Mánager Personal','drive','manage'::permission_level),
('Mánager Personal','roadmaps','manage'::permission_level),
('Mánager Personal','solicitudes','manage'::permission_level),
('Mánager Personal','analytics','manage'::permission_level),
('Mánager Personal','contacts','manage'::permission_level),
('Mánager Personal','automations','edit'::permission_level),
('Business Manager','bookings','view'::permission_level),
('Business Manager','budgets','manage'::permission_level),
('Business Manager','cashflow','manage'::permission_level),
('Business Manager','contracts','view'::permission_level),
('Business Manager','releases','none'::permission_level),
('Business Manager','projects','view'::permission_level),
('Business Manager','drive','view'::permission_level),
('Business Manager','roadmaps','none'::permission_level),
('Business Manager','solicitudes','edit'::permission_level),
('Business Manager','analytics','manage'::permission_level),
('Business Manager','contacts','view'::permission_level),
('Business Manager','automations','view'::permission_level),
('Director Artístico','bookings','view'::permission_level),
('Director Artístico','budgets','view'::permission_level),
('Director Artístico','cashflow','none'::permission_level),
('Director Artístico','contracts','none'::permission_level),
('Director Artístico','releases','manage'::permission_level),
('Director Artístico','projects','manage'::permission_level),
('Director Artístico','drive','edit'::permission_level),
('Director Artístico','roadmaps','view'::permission_level),
('Director Artístico','solicitudes','edit'::permission_level),
('Director Artístico','analytics','view'::permission_level),
('Director Artístico','contacts','view'::permission_level),
('Director Artístico','automations','view'::permission_level),
('Booker','bookings','manage'::permission_level),
('Booker','budgets','edit'::permission_level),
('Booker','cashflow','none'::permission_level),
('Booker','contracts','edit'::permission_level),
('Booker','releases','none'::permission_level),
('Booker','projects','view'::permission_level),
('Booker','drive','view'::permission_level),
('Booker','roadmaps','manage'::permission_level),
('Booker','solicitudes','edit'::permission_level),
('Booker','analytics','view'::permission_level),
('Booker','contacts','view'::permission_level),
('Booker','automations','none'::permission_level),
('Booking Agent','bookings','manage'::permission_level),
('Booking Agent','budgets','edit'::permission_level),
('Booking Agent','cashflow','view'::permission_level),
('Booking Agent','contracts','edit'::permission_level),
('Booking Agent','releases','none'::permission_level),
('Booking Agent','projects','view'::permission_level),
('Booking Agent','drive','view'::permission_level),
('Booking Agent','roadmaps','manage'::permission_level),
('Booking Agent','solicitudes','edit'::permission_level),
('Booking Agent','analytics','view'::permission_level),
('Booking Agent','contacts','edit'::permission_level),
('Booking Agent','automations','none'::permission_level),
('Tour Manager','bookings','edit'::permission_level),
('Tour Manager','budgets','view'::permission_level),
('Tour Manager','cashflow','none'::permission_level),
('Tour Manager','contracts','view'::permission_level),
('Tour Manager','releases','none'::permission_level),
('Tour Manager','projects','view'::permission_level),
('Tour Manager','drive','view'::permission_level),
('Tour Manager','roadmaps','manage'::permission_level),
('Tour Manager','solicitudes','edit'::permission_level),
('Tour Manager','analytics','view'::permission_level),
('Tour Manager','contacts','view'::permission_level),
('Tour Manager','automations','none'::permission_level),
('Road Manager','bookings','view'::permission_level),
('Road Manager','budgets','none'::permission_level),
('Road Manager','cashflow','none'::permission_level),
('Road Manager','contracts','none'::permission_level),
('Road Manager','releases','none'::permission_level),
('Road Manager','projects','view'::permission_level),
('Road Manager','drive','view'::permission_level),
('Road Manager','roadmaps','edit'::permission_level),
('Road Manager','solicitudes','edit'::permission_level),
('Road Manager','analytics','none'::permission_level),
('Road Manager','contacts','view'::permission_level),
('Road Manager','automations','none'::permission_level),
('A&R','bookings','view'::permission_level),
('A&R','budgets','view'::permission_level),
('A&R','cashflow','none'::permission_level),
('A&R','contracts','view'::permission_level),
('A&R','releases','manage'::permission_level),
('A&R','projects','edit'::permission_level),
('A&R','drive','edit'::permission_level),
('A&R','roadmaps','none'::permission_level),
('A&R','solicitudes','edit'::permission_level),
('A&R','analytics','view'::permission_level),
('A&R','contacts','view'::permission_level),
('A&R','automations','none'::permission_level),
('Productor','bookings','none'::permission_level),
('Productor','budgets','view'::permission_level),
('Productor','cashflow','none'::permission_level),
('Productor','contracts','view'::permission_level),
('Productor','releases','edit'::permission_level),
('Productor','projects','view'::permission_level),
('Productor','drive','edit'::permission_level),
('Productor','roadmaps','none'::permission_level),
('Productor','solicitudes','edit'::permission_level),
('Productor','analytics','none'::permission_level),
('Productor','contacts','view'::permission_level),
('Productor','automations','none'::permission_level),
('Productor Ejecutivo','bookings','view'::permission_level),
('Productor Ejecutivo','budgets','edit'::permission_level),
('Productor Ejecutivo','cashflow','view'::permission_level),
('Productor Ejecutivo','contracts','edit'::permission_level),
('Productor Ejecutivo','releases','manage'::permission_level),
('Productor Ejecutivo','projects','manage'::permission_level),
('Productor Ejecutivo','drive','edit'::permission_level),
('Productor Ejecutivo','roadmaps','view'::permission_level),
('Productor Ejecutivo','solicitudes','edit'::permission_level),
('Productor Ejecutivo','analytics','view'::permission_level),
('Productor Ejecutivo','contacts','view'::permission_level),
('Productor Ejecutivo','automations','view'::permission_level),
('Compositor','bookings','none'::permission_level),
('Compositor','budgets','none'::permission_level),
('Compositor','cashflow','none'::permission_level),
('Compositor','contracts','view'::permission_level),
('Compositor','releases','view'::permission_level),
('Compositor','projects','view'::permission_level),
('Compositor','drive','view'::permission_level),
('Compositor','roadmaps','none'::permission_level),
('Compositor','solicitudes','view'::permission_level),
('Compositor','analytics','none'::permission_level),
('Compositor','contacts','view'::permission_level),
('Compositor','automations','none'::permission_level),
('Letrista','bookings','none'::permission_level),
('Letrista','budgets','none'::permission_level),
('Letrista','cashflow','none'::permission_level),
('Letrista','contracts','view'::permission_level),
('Letrista','releases','view'::permission_level),
('Letrista','projects','view'::permission_level),
('Letrista','drive','view'::permission_level),
('Letrista','roadmaps','none'::permission_level),
('Letrista','solicitudes','view'::permission_level),
('Letrista','analytics','none'::permission_level),
('Letrista','contacts','view'::permission_level),
('Letrista','automations','none'::permission_level),
('Intérprete','bookings','view'::permission_level),
('Intérprete','budgets','none'::permission_level),
('Intérprete','cashflow','none'::permission_level),
('Intérprete','contracts','view'::permission_level),
('Intérprete','releases','view'::permission_level),
('Intérprete','projects','view'::permission_level),
('Intérprete','drive','view'::permission_level),
('Intérprete','roadmaps','view'::permission_level),
('Intérprete','solicitudes','edit'::permission_level),
('Intérprete','analytics','none'::permission_level),
('Intérprete','contacts','view'::permission_level),
('Intérprete','automations','none'::permission_level),
('Músico de Banda','bookings','view'::permission_level),
('Músico de Banda','budgets','none'::permission_level),
('Músico de Banda','cashflow','none'::permission_level),
('Músico de Banda','contracts','view'::permission_level),
('Músico de Banda','releases','view'::permission_level),
('Músico de Banda','projects','view'::permission_level),
('Músico de Banda','drive','view'::permission_level),
('Músico de Banda','roadmaps','view'::permission_level),
('Músico de Banda','solicitudes','edit'::permission_level),
('Músico de Banda','analytics','none'::permission_level),
('Músico de Banda','contacts','view'::permission_level),
('Músico de Banda','automations','none'::permission_level),
('Técnico de Sonido','bookings','view'::permission_level),
('Técnico de Sonido','budgets','none'::permission_level),
('Técnico de Sonido','cashflow','none'::permission_level),
('Técnico de Sonido','contracts','none'::permission_level),
('Técnico de Sonido','releases','none'::permission_level),
('Técnico de Sonido','projects','view'::permission_level),
('Técnico de Sonido','drive','view'::permission_level),
('Técnico de Sonido','roadmaps','view'::permission_level),
('Técnico de Sonido','solicitudes','edit'::permission_level),
('Técnico de Sonido','analytics','none'::permission_level),
('Técnico de Sonido','contacts','view'::permission_level),
('Técnico de Sonido','automations','none'::permission_level),
('Técnico de Luces','bookings','view'::permission_level),
('Técnico de Luces','budgets','none'::permission_level),
('Técnico de Luces','cashflow','none'::permission_level),
('Técnico de Luces','contracts','none'::permission_level),
('Técnico de Luces','releases','none'::permission_level),
('Técnico de Luces','projects','view'::permission_level),
('Técnico de Luces','drive','view'::permission_level),
('Técnico de Luces','roadmaps','view'::permission_level),
('Técnico de Luces','solicitudes','edit'::permission_level),
('Técnico de Luces','analytics','none'::permission_level),
('Técnico de Luces','contacts','view'::permission_level),
('Técnico de Luces','automations','none'::permission_level),
('Backliner','bookings','view'::permission_level),
('Backliner','budgets','none'::permission_level),
('Backliner','cashflow','none'::permission_level),
('Backliner','contracts','none'::permission_level),
('Backliner','releases','none'::permission_level),
('Backliner','projects','none'::permission_level),
('Backliner','drive','view'::permission_level),
('Backliner','roadmaps','view'::permission_level),
('Backliner','solicitudes','view'::permission_level),
('Backliner','analytics','none'::permission_level),
('Backliner','contacts','view'::permission_level),
('Backliner','automations','none'::permission_level),
('Comunicación / Prensa','bookings','view'::permission_level),
('Comunicación / Prensa','budgets','none'::permission_level),
('Comunicación / Prensa','cashflow','none'::permission_level),
('Comunicación / Prensa','contracts','none'::permission_level),
('Comunicación / Prensa','releases','edit'::permission_level),
('Comunicación / Prensa','projects','view'::permission_level),
('Comunicación / Prensa','drive','manage'::permission_level),
('Comunicación / Prensa','roadmaps','view'::permission_level),
('Comunicación / Prensa','solicitudes','edit'::permission_level),
('Comunicación / Prensa','analytics','view'::permission_level),
('Comunicación / Prensa','contacts','edit'::permission_level),
('Comunicación / Prensa','automations','view'::permission_level),
('Marketing Digital','bookings','view'::permission_level),
('Marketing Digital','budgets','view'::permission_level),
('Marketing Digital','cashflow','none'::permission_level),
('Marketing Digital','contracts','none'::permission_level),
('Marketing Digital','releases','edit'::permission_level),
('Marketing Digital','projects','view'::permission_level),
('Marketing Digital','drive','edit'::permission_level),
('Marketing Digital','roadmaps','none'::permission_level),
('Marketing Digital','solicitudes','edit'::permission_level),
('Marketing Digital','analytics','view'::permission_level),
('Marketing Digital','contacts','view'::permission_level),
('Marketing Digital','automations','edit'::permission_level),
('Community Manager','bookings','view'::permission_level),
('Community Manager','budgets','none'::permission_level),
('Community Manager','cashflow','none'::permission_level),
('Community Manager','contracts','none'::permission_level),
('Community Manager','releases','edit'::permission_level),
('Community Manager','projects','view'::permission_level),
('Community Manager','drive','edit'::permission_level),
('Community Manager','roadmaps','none'::permission_level),
('Community Manager','solicitudes','view'::permission_level),
('Community Manager','analytics','view'::permission_level),
('Community Manager','contacts','view'::permission_level),
('Community Manager','automations','view'::permission_level),
('Diseñador Gráfico','bookings','none'::permission_level),
('Diseñador Gráfico','budgets','none'::permission_level),
('Diseñador Gráfico','cashflow','none'::permission_level),
('Diseñador Gráfico','contracts','none'::permission_level),
('Diseñador Gráfico','releases','view'::permission_level),
('Diseñador Gráfico','projects','view'::permission_level),
('Diseñador Gráfico','drive','edit'::permission_level),
('Diseñador Gráfico','roadmaps','none'::permission_level),
('Diseñador Gráfico','solicitudes','edit'::permission_level),
('Diseñador Gráfico','analytics','none'::permission_level),
('Diseñador Gráfico','contacts','view'::permission_level),
('Diseñador Gráfico','automations','none'::permission_level),
('Fotógrafo','bookings','view'::permission_level),
('Fotógrafo','budgets','none'::permission_level),
('Fotógrafo','cashflow','none'::permission_level),
('Fotógrafo','contracts','none'::permission_level),
('Fotógrafo','releases','view'::permission_level),
('Fotógrafo','projects','view'::permission_level),
('Fotógrafo','drive','edit'::permission_level),
('Fotógrafo','roadmaps','none'::permission_level),
('Fotógrafo','solicitudes','edit'::permission_level),
('Fotógrafo','analytics','none'::permission_level),
('Fotógrafo','contacts','view'::permission_level),
('Fotógrafo','automations','none'::permission_level),
('Videógrafo','bookings','view'::permission_level),
('Videógrafo','budgets','none'::permission_level),
('Videógrafo','cashflow','none'::permission_level),
('Videógrafo','contracts','none'::permission_level),
('Videógrafo','releases','view'::permission_level),
('Videógrafo','projects','view'::permission_level),
('Videógrafo','drive','edit'::permission_level),
('Videógrafo','roadmaps','none'::permission_level),
('Videógrafo','solicitudes','edit'::permission_level),
('Videógrafo','analytics','none'::permission_level),
('Videógrafo','contacts','view'::permission_level),
('Videógrafo','automations','none'::permission_level),
('Asesor Legal','bookings','view'::permission_level),
('Asesor Legal','budgets','view'::permission_level),
('Asesor Legal','cashflow','view'::permission_level),
('Asesor Legal','contracts','manage'::permission_level),
('Asesor Legal','releases','view'::permission_level),
('Asesor Legal','projects','view'::permission_level),
('Asesor Legal','drive','edit'::permission_level),
('Asesor Legal','roadmaps','view'::permission_level),
('Asesor Legal','solicitudes','edit'::permission_level),
('Asesor Legal','analytics','view'::permission_level),
('Asesor Legal','contacts','view'::permission_level),
('Asesor Legal','automations','view'::permission_level),
('Asesor Fiscal','bookings','view'::permission_level),
('Asesor Fiscal','budgets','view'::permission_level),
('Asesor Fiscal','cashflow','manage'::permission_level),
('Asesor Fiscal','contracts','view'::permission_level),
('Asesor Fiscal','releases','none'::permission_level),
('Asesor Fiscal','projects','view'::permission_level),
('Asesor Fiscal','drive','view'::permission_level),
('Asesor Fiscal','roadmaps','none'::permission_level),
('Asesor Fiscal','solicitudes','view'::permission_level),
('Asesor Fiscal','analytics','view'::permission_level),
('Asesor Fiscal','contacts','view'::permission_level),
('Asesor Fiscal','automations','none'::permission_level),
('Sello Discográfico','bookings','view'::permission_level),
('Sello Discográfico','budgets','view'::permission_level),
('Sello Discográfico','cashflow','none'::permission_level),
('Sello Discográfico','contracts','edit'::permission_level),
('Sello Discográfico','releases','view'::permission_level),
('Sello Discográfico','projects','view'::permission_level),
('Sello Discográfico','drive','view'::permission_level),
('Sello Discográfico','roadmaps','none'::permission_level),
('Sello Discográfico','solicitudes','view'::permission_level),
('Sello Discográfico','analytics','view'::permission_level),
('Sello Discográfico','contacts','view'::permission_level),
('Sello Discográfico','automations','none'::permission_level),
('Editorial','bookings','none'::permission_level),
('Editorial','budgets','view'::permission_level),
('Editorial','cashflow','none'::permission_level),
('Editorial','contracts','edit'::permission_level),
('Editorial','releases','view'::permission_level),
('Editorial','projects','view'::permission_level),
('Editorial','drive','view'::permission_level),
('Editorial','roadmaps','none'::permission_level),
('Editorial','solicitudes','view'::permission_level),
('Editorial','analytics','view'::permission_level),
('Editorial','contacts','view'::permission_level),
('Editorial','automations','none'::permission_level),
('Distribuidor','bookings','none'::permission_level),
('Distribuidor','budgets','view'::permission_level),
('Distribuidor','cashflow','none'::permission_level),
('Distribuidor','contracts','edit'::permission_level),
('Distribuidor','releases','view'::permission_level),
('Distribuidor','projects','view'::permission_level),
('Distribuidor','drive','view'::permission_level),
('Distribuidor','roadmaps','none'::permission_level),
('Distribuidor','solicitudes','view'::permission_level),
('Distribuidor','analytics','view'::permission_level),
('Distribuidor','contacts','view'::permission_level),
('Distribuidor','automations','none'::permission_level),
('Promotor','bookings','view'::permission_level),
('Promotor','budgets','view'::permission_level),
('Promotor','cashflow','none'::permission_level),
('Promotor','contracts','view'::permission_level),
('Promotor','releases','none'::permission_level),
('Promotor','projects','none'::permission_level),
('Promotor','drive','view'::permission_level),
('Promotor','roadmaps','view'::permission_level),
('Promotor','solicitudes','view'::permission_level),
('Promotor','analytics','none'::permission_level),
('Promotor','contacts','view'::permission_level),
('Promotor','automations','none'::permission_level)
ON CONFLICT (role_name, module) DO UPDATE SET level = EXCLUDED.level, updated_at = now();