import { z } from 'zod';
import { supabase } from '@/integrations/supabase/client';

// ─── Schemas ──────────────────────────────────────────────────────────
export const budgetNameSchema = z
  .string()
  .trim()
  .min(1, 'El nombre no puede estar vacío')
  .max(120, 'El nombre es demasiado largo (máx. 120)');

// Fields we never copy when duplicating a budget header
// (auto-generated by DB, fiscal/accounting state, or "primary" flag).
const HEADER_EXCLUDED_FIELDS = new Set<string>([
  'id',
  'created_at',
  'updated_at',
  'created_by',
  'is_primary_for_booking', // copy never inherits primary flag
  'accountant_verified_at',
  'accountant_verified_by',
  'estimated_version_id',
  'final_version_id',
  'settlement_status',
  'status_negociacion',
]);

const ITEM_EXCLUDED_FIELDS = new Set<string>([
  'id',
  'budget_id',
  'created_at',
  'updated_at',
  // Reset reconciliation/invoicing state on a fresh copy
  'is_reconciled',
  'reconciled_at',
  'reconciled_by',
  'billing_status',
  'invoice_group_parent_id',
  'invoice_link',
  'fecha_emision',
  'provider_invoice_received_at',
  'provider_invoice_requested_at',
  'provider_invoice_status',
  'supplier_invoice_number',
  'supplier_invoice_total',
]);

function pickAllowed<T extends Record<string, any>>(
  row: T,
  excluded: Set<string>
): Partial<T> {
  const out: Record<string, any> = {};
  for (const [k, v] of Object.entries(row)) {
    if (excluded.has(k)) continue;
    out[k] = v;
  }
  return out as Partial<T>;
}

// ─── Rename ───────────────────────────────────────────────────────────
export async function renameBudget(budgetId: string, newName: string) {
  const parsed = budgetNameSchema.safeParse(newName);
  if (!parsed.success) {
    throw new Error(parsed.error.issues[0]?.message || 'Nombre inválido');
  }

  const { data, error } = await supabase
    .from('budgets')
    .update({ name: parsed.data })
    .eq('id', budgetId)
    .select('id, name')
    .single();

  if (error) throw error;
  return data;
}

// ─── Duplicate ────────────────────────────────────────────────────────
const PAGE_SIZE = 500;

export async function duplicateBudget(sourceBudgetId: string, userId: string) {
  if (!sourceBudgetId) throw new Error('Falta el id del presupuesto origen');
  if (!userId) throw new Error('Usuario no autenticado');

  // 1. Read source header
  const { data: source, error: srcErr } = await supabase
    .from('budgets')
    .select('*')
    .eq('id', sourceBudgetId)
    .single();

  if (srcErr || !source) {
    throw new Error('No se pudo leer el presupuesto origen');
  }

  // 2. Build new header (strip excluded + auto fields, force new name + creator)
  const headerInsert: Record<string, any> = {
    ...pickAllowed(source, HEADER_EXCLUDED_FIELDS),
    name: `${source.name} (copia)`.slice(0, 120),
    created_by: userId,
    is_primary_for_booking: false,
  };

  const { data: newBudget, error: insErr } = await supabase
    .from('budgets')
    .insert(headerInsert as any)
    .select('*')
    .single();

  if (insErr || !newBudget) {
    throw new Error(insErr?.message || 'No se pudo duplicar el presupuesto');
  }

  // 3. Copy items in pages
  try {
    let from = 0;
    while (true) {
      const { data: items, error: itemsErr } = await supabase
        .from('budget_items')
        .select('*')
        .eq('budget_id', sourceBudgetId)
        .range(from, from + PAGE_SIZE - 1);

      if (itemsErr) throw itemsErr;
      if (!items || items.length === 0) break;

      const toInsert = items.map((it) => ({
        ...pickAllowed(it, ITEM_EXCLUDED_FIELDS),
        budget_id: newBudget.id,
      }));

      if (toInsert.length > 0) {
        const { error: insItemsErr } = await supabase
          .from('budget_items')
          .insert(toInsert as any);
        if (insItemsErr) throw insItemsErr;
      }

      if (items.length < PAGE_SIZE) break;
      from += PAGE_SIZE;
    }
  } catch (e) {
    // Rollback: delete the new header so we don't leave it half-populated
    await supabase.from('budgets').delete().eq('id', newBudget.id);
    throw e instanceof Error
      ? e
      : new Error('Error al duplicar las partidas del presupuesto');
  }

  return newBudget;
}
